### ISSUE TITLE
Issue between Rich Text Editor, this plugin and Firefox

### ISSUE THREAD

**Issue by luisrcastro85** [alan-null/sc_ext#107]
### Steps to Reproduce the Problem
  1. Open Firefox
  2. Open a Sitecore Content Editor window
  3. Select an item with a Rich Text field
  4. Make sure that Rich Text field is empty
  4. Click "Show Editor"
  5. In the Rich Text Editor popup, change from "Design" view to "HTML" view
  
### Expected Behavior 
No html should exist in the editor

### Actual Behavior
The following weird html code is added automatically:
`<br />`
`<div id="sc-ext-modal" class="launcher-modal">`
`<div class="launcher-modal-content"><input id="sc-ext-searchBox" class="search-field" />`
`<ul id="sc-ext-searchResults" class="term-list hidden"></ul>`
`</div>`
`</div>`
If I disable the extension in Firefox, then that weird code is not generated and everything works as expected.

### Specifications
Sitecore version: 8.2 (rev. 161115)
Sitecore eXtensions: 3.1.0.1

**Comment by alan-null** [comment]
Hi @luisrcastro85,

Thank you for report. I really appreciate it
This issue was already addressed ( #75 #106 )  and will be fixed in the next public release (I will submit package to the Firefox store in the next week)

I will leave this issue open until the release just in case someone else report it again ;)

**Comment by alan-null** [comment]
Issue solved, fix published.
Make sure you use self-hosted extension
https://alan-null.github.io/2017/09/sitecore-extensions-ff
