### ISSUE TITLE
Navigating with launcher removes Sitecore menu

### ISSUE THREAD

**Issue by chbj** [alan-null/sc_ext#73]
### Steps to Reproduce the Problem
  1. Log in to sitecore
  2. From desktop, open launcher and navigate to User Manager
  
### Expected Behavior 
Launch of User Manager with the bottom menu bar still there

### Actual Behavior
Launch of User Manager - menu bar is now gone

### Specifications
Sitecore version: 7.2 (revision 140526)

**Comment by alan-null** [comment]
Hi @chbj,

Thank you for reporting. This is expected behaviour right now.

Bottom menu disappears because I am opening directly an application (notice that url changes). 

By default, each navigation command will be opened in your current window. If you want to open command in a new tab, use `Ctrl + Enter` when executing a command from Launcher. 

Although this is possible to bring tabbed experience for those dialogs this is not critical for now.
